# Generated by Django 3.2.4 on 2021-11-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Autor')),
                ('nombreAutor', models.CharField(max_length=50, verbose_name='Nombre de Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de Libro')),
                ('editorial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Editorial')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('fechaReserva', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libro')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
